# Generated by Django 4.2.6 on 2023-11-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(blank=True, max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=20, unique=True)),
                ('inscestadual', models.CharField(blank=True, max_length=15)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=2)),
            ],
        ),
    ]
