# Generated by Django 4.2.6 on 2023-11-05 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientepf',
            old_name='cnpj',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='clientepf',
            old_name='inscestadual',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='clientepf',
            name='razaosocial',
        ),
        migrations.CreateModel(
            name='ClientePj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('inscestadual', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.cliente', unique=True)),
            ],
        ),
    ]
